hard_tabs = true
max_width = 80
newline_style = "Unix"
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
