[package]
name = "audio"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cpal = "0.14.2"
symphonia = { version = "0.5.1", features = ["mp3"] }
