[package]
name = "astral-player"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
crossterm = "0.25.0"
rodio = { version = "0.16.0", features = ["symphonia-all"] }
